openapi: 3.0.1
info:
  title: Product API
  description: API para manejar productos
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Obtener una lista de productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Crear un nuevo producto
      responses:
        '201':
          description: Producto creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/products/{pid}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: ID del producto
      responses:
        '200':
          description: Producto único
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      summary: Actualizar un producto
      responses:
        '200':
          description: Producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      summary: Eliminar un producto
      responses:
        '204':
          description: Producto eliminado
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        status:
          type: boolean
        stock:
          type: number
        category:
          type: string
        thumbnails:
          type: array
          items:
            type: string
        owner:
          type: string
